# Generated by Django 5.1.7 on 2025-03-31 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserA',
        ),
    ]
