# Generated by Django 5.2 on 2025-04-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('roll', models.IntegerField()),
                ('city', models.CharField(max_length=80)),
                ('marks', models.IntegerField()),
                ('passed_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('pass_key', models.IntegerField()),
                ('city', models.CharField(max_length=80)),
                ('salary', models.IntegerField()),
                ('joined_date', models.DateField()),
            ],
        ),
    ]
