# Generated by Django 5.2 on 2025-04-11 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=90)),
                ('city', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='MyExamCenter',
            fields=[
                ('examcenter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='school.examcenter')),
                ('name', models.CharField(max_length=90)),
                ('roll', models.CharField(max_length=90)),
            ],
            bases=('school.examcenter',),
        ),
    ]
