# Generated by Django 5.2 on 2025-06-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='link',
            new_name='like_count',
        ),
    ]
