# Generated by Django 5.2 on 2025-06-13 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_link_like_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='page',
        ),
        migrations.AddField(
            model_name='like',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default='default_value', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.page'),
            preserve_default=False,
        ),
    ]
