# Generated by Django 5.2 on 2025-06-13 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_like_page_like_page_ptr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='like',
            name='page',
            field=models.OneToOneField(default='default_value', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.page'),
            preserve_default=False,
        ),
    ]
